### PR TITLE
CASMTRIAGE-3173: Changing the netX boot order

### PR DESCRIPTION
**Pull request by jsollom-hpe**
## Summary and Scope

This is to work around long delays in booting on Surtur. I made this PR on @alexanderkingh 's behalf.

I have concerns about this change because we made net2 first for a specific reason, which I cannot remember.
## Issues and Related PRs

CASMTRIAGE-3173
* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

### CODE REVIEW

**Comment by alexanderkingh** [comment]
FYI please feel free to [read this JIRA comment in CASMTRIAGE-3173](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3173?focusedCommentId=4789341&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4789341) for a summary of the analysis and issue leading to this PR. Will be testing this via a bss config-map change from the already documented operations procedure located here [Edit_the_iPXE_Embedded_Boot_Script.md](https://github.com/Cray-HPE/docs-csm/blob/main/operations/boot_orchestration/Edit_the_iPXE_Embedded_Boot_Script.md)

**Comment by rnoska-hpe** [comment]
It was always my understanding that net2 was chosen as the first dhcp interface in order to minimize the dhcp request time (and therefore overall boot time) across the majority of our deployments.  IIRC net2 was likely the most common interface cabled to the node management network where the expected dhcp service was running. Based on my read of this ticket it seems net0 is now preferred, but is this ipxe now being used to boot management nodes?  And, if so, how does this proposed change affect boot times for compute or other types of non-management nodes?

**Comment by alexanderkingh** [comment]
> It was always my understanding that net2 was chosen as the first dhcp interface in order to minimize the dhcp request time (and therefore overall boot time) across the majority of our deployments. IIRC net2 was likely the most common interface cabled to the node management network where the expected dhcp service was running. Based on my read of this ticket it seems net0 is now preferred, but is this ipxe now being used to boot management nodes? And, if so, how does this proposed change affect boot times for compute or other types of non-management nodes?

For NCNs, yes we made an explicit choice in 1.2 to change switch config and bss hand off to prefer net0 that dramatically improved initial NCN pxe boot.

Actually CMS-iPXE has been used for a long time for ncn-m001, for at least the last ~5 months I have been here but i think quite a bit longer. All the NCNs except ncn-m001 boot off of boot script info served from the PIT. ncn-m001 boots off CMS-iPXE currently because it is the pit and can't serve the boot script itself so as currently designed, needs to boot from CMS-iPXE.

**Comment by rustydb** [comment]
I think this needs to be tested with computes and UANs.

Ideally we'd switch ncn-m001 to boot off metal-ipxe, but it isn't containerized let alone running in k8s.

**Review by heemstra — APPROVED** [review]

**Comment by heemstra** [comment]
Just to clarify, all management nodes boot off of csm-ipxe after initial deployment. Once the pit is deployed as m001, all subsequent reboots or rebuilds leverage kea and csm-ipxe.

**Comment by alexanderkingh** [comment]
I have updated the JIRA with comments and possible next steps that I would like review on. I updated the jira as more people replied in the JIRA. And I have closed PR 39 which was just used as a PR to get a change in a fork created from which this branch was created.

**Comment by jsollom-hpe** [comment]
I don't think we need this PR.

**Pull request closed without merging**
